#ifndef __uppmain__
#define __uppmain__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "uppmainwindow.h"

/** Implementing MyFrame1 */
class uppmain : public MyFrame1
{
public:
	/** Constructor */
	uppmain( wxWindow* parent );
};

#endif // __uppmain__
