#ifndef __usbpicprogMyFrame1__
#define __usbpicprogMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "uppmainwindow.h"

/** Implementing MyFrame1 */
class usbpicprogMyFrame1 : public MyFrame1
{
public:
	/** Constructor */
	usbpicprogMyFrame1( wxWindow* parent );
};

#endif // __usbpicprogMyFrame1__
