all:
	@echo "This Makefile is only for the SVN repository"
	@echo ""
	@if test ! -d admin; then \
	   echo "Please update this module!" ;\
	   exit 1 ;\
	fi
	@echo "Extract messages"
	$(MAKE) -f admin/Makefile.common package-messages
	cd po && sh merge.sh
	@echo ""
	@echo "Create configure & co"
	$(MAKE) -f admin/Makefile.common cvs

messages:
	@echo "Extract messages"
	$(MAKE) -f admin/Makefile.common package-messages
	cd po && sh merge.sh

.SILENT:
