// generated 2008/4/18 16:36:03 CEST by frans@asus-laptop.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/frans/usbpicprog/trunk/upp_gui/usbpicprog.glade
// for gtk 2.12.0 and gtkmm 2.12.0
//
// Please modify the corresponding derived classes in ./src/uppMainWindow.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "uppMainWindow_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtk/gtkimagemenuitem.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#include <gdkmm/pixbufloader.h>

static const unsigned char hi22_action_piklab_burnchip_png_data[] = 
{       	137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,
	0,0,0,22,0,0,0,22,8,6,0,0,0,196,180,108,
	59,0,0,0,6,98,75,71,68,0,255,0,255,0,255,160,
	189,167,147,0,0,0,9,112,72,89,115,0,0,11,17,0,
	0,11,17,1,127,100,95,145,0,0,0,7,116,73,77,69,
	7,210,11,13,16,50,8,233,21,129,123,0,0,3,165,73,
	68,65,84,120,156,173,148,79,72,35,73,20,198,191,78,135,
	8,35,145,140,216,104,46,70,146,86,28,49,26,80,155,40,
	146,173,176,135,12,3,34,254,65,115,28,193,195,232,201,227,
	128,135,73,31,148,224,117,97,46,6,241,224,193,195,162,193,
	85,183,145,64,183,196,117,156,168,135,156,12,249,59,138,134,
	136,67,230,32,68,23,98,106,15,218,49,137,50,51,203,238,
	7,143,87,93,253,248,245,87,175,186,10,184,23,1,64,31,
	242,255,34,6,0,33,4,178,44,3,78,39,160,40,112,2,
	80,42,11,167,167,167,229,246,246,118,162,209,104,16,8,4,
	16,139,197,68,0,74,56,28,126,82,171,138,82,250,24,132,
	60,117,62,49,49,33,103,50,25,74,41,165,94,175,151,142,
	140,140,208,222,222,94,42,8,2,237,236,236,124,118,149,26,
	0,78,167,243,113,66,150,1,66,32,171,112,155,205,230,97,
	89,150,172,175,175,195,235,245,226,240,240,16,233,116,26,215,
	215,215,96,89,22,0,228,231,224,204,67,46,182,67,149,211,
	9,188,120,241,70,153,159,159,39,251,251,251,8,4,2,224,
	121,30,146,36,129,97,24,216,237,125,56,56,216,71,115,115,
	51,0,32,22,139,57,75,219,162,121,200,138,162,60,117,158,
	203,109,147,203,203,75,100,179,89,244,247,247,35,26,141,194,
	110,183,227,238,238,14,159,62,253,5,187,189,79,133,130,231,
	249,50,231,12,202,245,172,243,186,186,81,124,253,250,59,8,
	1,206,207,39,177,183,183,7,141,70,83,12,158,231,193,48,
	12,226,241,184,24,14,135,61,165,142,85,41,44,251,171,82,
	233,188,171,235,15,168,31,43,20,10,200,231,243,197,48,153,
	76,160,148,194,96,48,148,129,202,192,54,155,205,51,53,53,
	69,222,189,91,69,41,252,253,251,191,139,227,82,176,201,100,
	2,195,48,168,173,173,133,207,231,3,199,113,197,58,86,29,
	140,142,142,202,14,135,227,173,207,231,67,34,145,64,77,77,
	7,98,177,24,28,142,66,177,120,119,23,200,102,59,144,72,
	36,96,177,88,160,211,233,144,74,165,32,73,210,61,140,101,
	201,218,218,154,88,116,60,52,52,36,143,143,143,147,177,177,
	49,52,52,52,160,163,163,3,223,190,249,49,59,155,71,165,
	10,133,2,154,154,154,160,213,106,145,76,38,209,211,211,3,
	171,213,42,46,46,46,98,115,115,83,84,235,180,0,208,216,
	216,72,204,102,51,150,150,150,16,143,199,161,211,233,224,112,
	220,65,20,203,161,138,2,244,247,55,33,157,78,35,149,74,
	97,101,101,5,39,39,39,88,94,94,246,108,111,255,249,193,
	239,95,247,148,129,143,143,143,21,73,146,192,243,60,137,70,
	163,104,107,107,67,56,60,4,134,97,202,162,183,151,71,48,
	24,196,217,217,25,102,102,102,32,8,2,172,86,43,36,73,
	242,68,34,145,50,27,140,186,105,23,23,23,0,240,65,16,
	4,108,109,109,221,191,124,0,106,52,26,180,180,180,192,96,
	48,224,252,252,28,125,125,125,8,133,66,162,203,229,250,69,
	175,215,147,133,133,133,202,223,246,241,128,168,19,161,80,8,
	3,3,3,0,238,47,17,181,167,122,189,30,167,167,167,88,
	93,93,5,33,4,201,100,210,243,234,149,85,220,217,217,17,
	43,161,79,196,113,28,229,56,142,26,141,70,58,56,56,72,
	1,80,139,197,66,187,186,186,104,125,125,61,157,155,155,163,
	145,72,132,110,108,108,80,183,219,237,81,87,251,51,96,162,
	194,205,102,51,29,30,30,166,221,221,221,148,227,56,234,247,
	251,169,209,104,148,93,46,151,60,57,57,73,127,196,98,75,
	31,114,185,220,151,234,234,234,93,0,111,11,133,2,114,185,
	28,170,170,170,48,59,59,139,154,154,26,104,181,218,47,47,
	95,214,137,159,63,31,156,102,50,25,229,121,228,189,42,143,
	52,174,174,174,20,0,206,124,62,143,155,155,27,0,64,48,
	24,196,209,209,17,110,111,111,241,241,227,111,223,5,254,80,
	28,199,145,214,214,86,42,8,130,7,0,94,191,126,67,221,
	110,55,249,79,208,231,244,83,155,84,162,39,173,248,142,148,
	127,3,254,7,116,164,147,48,33,178,1,157,0,0,0,0,
	73,69,78,68,174,66,96,130,

};
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
static const unsigned char hi22_action_piklab_readchip_png_data[] = 
{       	137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,
	0,0,0,22,0,0,0,22,8,6,0,0,0,196,180,108,
	59,0,0,0,6,98,75,71,68,0,255,0,255,0,255,160,
	189,167,147,0,0,0,9,112,72,89,115,0,0,11,17,0,
	0,11,17,1,127,100,95,145,0,0,0,7,116,73,77,69,
	7,210,11,13,16,37,31,111,69,128,42,0,0,3,181,73,
	68,65,84,120,156,165,211,77,72,27,105,24,7,240,127,62,
	252,78,66,26,118,144,156,204,26,19,45,42,17,148,96,182,
	44,204,184,5,75,65,212,40,152,163,130,135,234,33,94,188,
	121,200,204,193,212,251,66,65,200,65,244,226,94,84,60,236,
	65,197,153,34,106,12,177,32,94,242,97,162,9,40,81,33,
	10,66,76,73,204,179,7,141,155,164,105,237,178,127,120,152,
	153,151,119,126,188,239,243,206,200,0,176,79,85,46,252,119,
	198,95,140,18,0,203,178,112,177,37,180,36,61,86,30,159,
	156,156,20,219,218,218,88,185,92,142,173,173,45,132,195,97,
	1,128,116,116,116,36,125,15,231,121,30,68,244,111,137,34,
	8,128,152,159,48,54,54,38,38,18,9,34,34,154,155,155,
	163,161,161,33,178,217,108,100,181,90,201,98,177,176,229,80,
	101,185,65,65,120,188,0,64,71,71,7,175,80,40,216,213,
	213,85,220,222,222,194,239,247,227,226,226,2,119,119,119,80,
	171,213,0,32,90,44,22,174,116,229,101,97,81,4,56,14,
	98,109,237,123,201,237,118,179,123,123,123,216,220,220,68,46,
	151,195,233,233,41,0,224,205,155,223,225,245,238,193,100,50,
	225,105,119,69,184,60,127,35,73,128,76,86,140,167,82,127,
	179,151,151,151,72,38,147,72,167,211,8,6,131,200,100,50,
	120,120,120,192,254,254,46,186,187,127,3,0,132,195,97,52,
	53,53,137,133,109,145,231,81,142,131,4,128,227,184,98,252,
	227,199,94,28,31,31,11,129,64,0,153,76,6,217,108,246,
	185,118,119,119,16,10,133,96,52,26,243,175,20,193,188,36,
	65,0,192,1,144,20,138,63,164,82,252,242,242,47,87,50,
	153,20,10,209,124,53,52,52,128,136,160,213,106,139,218,153,
	111,5,159,63,168,137,137,9,246,195,135,101,148,226,29,29,
	183,174,155,155,27,161,20,149,201,100,208,233,116,240,120,60,
	96,24,230,27,24,195,195,195,226,192,192,128,203,237,118,99,
	113,113,17,95,191,218,138,86,94,81,81,137,154,154,154,103,
	212,96,48,64,161,80,32,18,137,192,227,241,0,0,70,71,
	71,93,249,249,74,0,24,28,28,20,71,70,70,216,214,214,
	86,248,124,62,196,227,113,68,163,81,54,155,173,20,222,190,
	125,112,201,100,50,124,249,162,18,228,242,172,75,46,151,195,
	108,54,67,169,84,34,26,141,162,187,187,27,237,237,237,130,
	211,233,116,109,111,111,11,69,253,152,154,154,162,195,195,67,
	154,158,158,38,179,217,76,74,165,146,42,43,43,169,186,186,
	154,106,107,107,121,149,74,197,107,52,26,210,106,181,100,181,
	90,169,167,167,135,76,38,19,29,28,28,208,194,194,2,1,
	192,192,192,32,21,154,138,199,109,86,176,75,75,75,103,185,
	92,206,224,245,122,139,127,67,34,246,169,96,52,26,161,82,
	169,16,139,197,224,116,58,97,183,219,209,220,220,140,72,36,
	34,59,57,57,249,156,72,36,164,34,88,167,211,253,122,117,
	117,21,59,63,63,103,57,142,67,40,20,42,197,97,52,26,
	161,86,171,17,143,199,97,179,217,176,178,178,34,4,131,65,
	236,239,239,27,230,231,231,185,66,180,240,240,158,7,125,62,
	31,250,250,250,0,0,68,132,92,46,7,131,193,0,181,90,
	141,88,44,134,229,229,101,176,44,139,104,52,202,191,126,221,
	46,108,108,108,20,247,181,92,24,134,33,134,97,72,175,215,
	83,127,127,63,1,32,163,209,72,157,157,157,84,95,95,79,
	179,179,179,20,8,4,104,125,125,157,28,14,7,15,60,126,
	162,63,3,179,121,188,177,177,145,236,118,59,117,117,117,17,
	195,48,180,182,182,70,122,189,94,236,237,237,21,199,199,199,
	233,37,75,81,248,144,74,165,206,234,234,234,62,3,24,205,
	229,114,72,165,82,168,170,170,194,204,204,12,52,26,13,148,
	74,229,217,171,87,191,8,7,7,222,88,105,79,75,35,47,
	29,184,190,190,150,0,112,217,108,22,247,247,247,0,128,157,
	157,29,248,253,126,164,211,105,124,250,244,231,15,193,23,195,
	48,12,219,210,210,66,86,171,149,7,128,119,239,222,147,195,
	225,96,255,23,90,46,63,117,72,5,249,166,21,63,136,244,
	95,224,127,0,167,179,226,49,34,197,237,46,0,0,0,0,
	73,69,78,68,174,66,96,130,

};
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
static const unsigned char hi22_action_piklab_erasechip_png_data[] = 
{       	137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,
	0,0,0,22,0,0,0,22,8,6,0,0,0,196,180,108,
	59,0,0,0,6,98,75,71,68,0,255,0,255,0,255,160,
	189,167,147,0,0,0,9,112,72,89,115,0,0,11,17,0,
	0,11,17,1,127,100,95,145,0,0,0,7,116,73,77,69,
	7,210,11,13,17,8,18,48,28,204,79,0,0,3,178,73,
	68,65,84,120,156,181,148,77,72,91,89,24,134,223,92,35,
	58,138,127,209,139,10,65,81,19,53,154,209,139,17,81,17,
	140,182,104,137,136,63,113,113,21,10,17,178,209,69,237,66,
	92,212,205,149,34,21,92,201,64,23,34,34,69,168,224,70,
	92,58,129,27,171,182,70,227,194,141,8,129,84,169,35,17,
	65,20,33,74,19,243,206,98,38,197,96,218,58,51,204,179,
	60,156,239,249,126,206,225,3,254,39,52,143,189,56,60,60,
	172,154,205,102,171,32,8,112,185,92,240,249,124,19,0,220,
	251,251,251,238,127,157,125,112,112,80,13,4,2,36,201,169,
	169,41,218,237,118,54,52,52,176,174,174,142,213,213,213,214,
	120,49,9,63,147,74,146,164,232,245,122,199,213,213,21,92,
	46,23,188,94,47,78,79,79,113,125,125,141,228,228,100,132,
	66,33,71,94,94,222,250,217,217,217,209,163,197,3,3,3,
	234,244,244,180,35,28,14,195,229,114,225,228,228,4,126,191,
	31,161,80,8,141,141,77,248,252,217,15,163,209,136,236,236,
	108,71,98,98,98,140,92,248,81,165,67,67,67,86,147,201,
	132,139,139,11,84,85,93,224,213,171,223,17,10,133,112,119,
	119,135,79,159,182,80,95,223,8,0,240,249,124,48,24,12,
	234,253,177,104,191,39,77,75,75,107,222,221,221,133,170,170,
	248,250,117,13,175,95,111,194,227,249,5,225,112,24,130,32,
	64,16,4,108,109,109,64,16,4,24,12,134,104,168,21,128,
	59,174,216,110,183,171,78,167,211,106,177,88,224,116,58,113,
	121,121,137,245,245,77,108,111,39,99,102,38,3,239,222,125,
	193,243,231,122,68,34,17,8,130,0,163,209,8,146,200,202,
	202,138,241,196,140,66,146,36,165,191,191,223,90,81,81,129,
	249,249,121,24,12,127,224,205,155,109,216,237,58,212,215,223,
	226,253,251,0,72,34,20,10,33,28,14,163,176,176,16,26,
	141,6,58,157,14,115,115,115,16,69,241,97,251,125,125,125,
	170,162,40,172,169,169,161,205,102,227,139,23,85,36,193,205,
	77,45,115,114,114,216,221,157,73,18,252,248,49,137,122,189,
	158,173,173,173,180,217,108,172,172,172,100,148,197,197,69,198,
	72,123,122,122,212,229,229,101,30,28,28,208,102,179,209,108,
	54,147,4,63,124,72,96,71,71,42,55,55,181,212,233,116,
	236,234,202,32,9,6,2,38,182,181,181,177,188,188,156,14,
	135,131,102,179,89,153,157,157,165,44,203,74,140,120,100,100,
	132,123,123,123,28,29,29,101,105,105,41,181,90,45,159,62,
	213,146,196,183,4,25,25,25,204,204,204,228,203,151,18,91,
	91,91,105,52,26,233,241,120,184,176,176,64,0,232,238,238,
	137,173,22,0,154,154,154,212,178,178,50,181,163,163,131,0,
	168,209,104,40,8,2,159,60,73,248,91,44,48,37,37,133,
	146,36,177,185,185,153,69,69,69,156,153,153,33,73,6,131,
	65,202,178,172,72,146,164,60,16,75,146,164,136,162,168,136,
	162,200,168,60,154,160,165,69,32,9,158,156,24,217,216,216,
	200,130,130,2,202,178,204,226,226,98,101,104,104,72,29,27,
	27,123,88,233,189,95,225,142,30,236,236,236,160,179,179,19,
	0,64,18,170,26,129,211,89,2,187,93,135,227,227,99,44,
	45,45,193,106,181,194,239,247,43,38,211,175,19,107,107,107,
	19,241,196,49,136,162,72,81,20,153,159,159,207,174,174,46,
	2,96,73,73,9,45,22,11,115,115,115,57,57,57,201,195,
	195,67,174,174,174,126,123,168,184,35,136,35,182,70,229,197,
	197,197,236,237,237,101,109,109,45,69,81,228,202,202,10,243,
	243,243,213,246,246,118,213,233,116,198,109,255,62,49,75,40,
	24,12,30,165,166,166,174,3,112,68,34,17,4,131,65,36,
	37,37,97,124,124,28,233,233,233,208,106,181,71,89,89,57,
	19,30,207,246,113,32,16,112,199,87,254,197,131,37,116,126,
	126,238,6,208,18,14,135,113,115,115,3,0,216,216,216,128,
	215,235,197,237,237,45,222,190,253,237,135,194,159,34,138,162,
	181,188,188,156,117,117,117,10,0,60,123,102,163,44,203,214,
	255,36,141,199,163,30,233,30,223,221,199,113,112,255,19,241,
	159,133,224,199,65,81,219,110,131,0,0,0,0,73,69,78,
	68,174,66,96,130,

};
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
static const unsigned char hi22_action_piklab_verifychip_png_data[] = 
{       	137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,
	0,0,0,22,0,0,0,22,8,6,0,0,0,196,180,108,
	59,0,0,0,6,98,75,71,68,0,255,0,255,0,255,160,
	189,167,147,0,0,0,9,112,72,89,115,0,0,11,17,0,
	0,11,17,1,127,100,95,145,0,0,0,7,116,73,77,69,
	7,210,11,13,17,25,43,60,192,103,87,0,0,3,173,73,
	68,65,84,120,156,181,149,79,72,27,89,28,199,191,153,78,
	254,144,168,104,186,179,68,132,226,106,38,138,27,215,208,104,
	32,149,133,23,93,177,44,8,53,138,127,192,195,30,114,242,
	160,80,220,94,60,52,57,46,189,117,193,42,138,8,226,85,
	68,60,10,147,54,168,145,234,65,144,110,98,226,104,130,150,
	144,160,148,178,140,174,12,243,235,65,147,234,106,173,187,203,
	126,225,119,120,195,227,243,62,191,55,143,247,128,255,41,186,
	187,78,28,28,28,148,156,78,39,227,56,14,203,203,203,72,
	36,18,33,0,225,173,173,173,240,77,243,185,59,48,153,213,
	106,149,120,158,103,217,108,22,7,7,7,32,34,152,205,230,
	231,70,163,81,106,104,104,96,255,198,56,200,24,158,75,210,
	231,15,62,31,112,124,252,3,52,77,67,113,113,49,20,69,
	1,0,223,223,205,111,51,102,193,224,57,52,20,58,175,183,
	111,45,144,36,224,193,3,25,205,205,63,66,81,20,136,162,
	8,81,20,175,153,223,102,44,17,129,249,124,0,207,255,4,
	131,193,128,189,189,61,188,123,247,7,94,189,250,22,227,227,
	54,120,189,205,56,58,202,33,145,72,192,110,183,35,153,76,
	22,204,249,155,136,46,151,43,248,240,225,71,22,10,201,200,
	229,190,71,121,57,16,139,197,192,113,231,13,106,154,6,85,
	85,177,178,18,1,199,113,176,219,237,133,46,1,220,12,238,
	234,234,146,2,129,0,115,187,221,8,4,2,184,127,255,67,
	1,250,244,233,71,0,192,218,154,17,170,170,130,227,56,136,
	162,8,34,66,89,89,217,21,206,21,176,203,229,10,246,247,
	247,179,186,186,58,76,79,79,35,155,205,66,150,101,60,123,
	118,130,71,143,206,224,245,254,133,104,212,132,149,21,61,56,
	78,133,40,138,208,233,116,176,90,173,152,154,154,66,91,91,
	219,245,61,238,238,238,150,156,78,39,91,92,92,132,205,102,
	67,38,147,129,44,203,224,56,14,71,71,199,23,221,88,17,
	141,154,192,113,28,28,14,7,76,38,19,82,169,20,182,183,
	183,1,0,115,115,115,24,24,24,208,1,23,167,162,179,179,
	83,234,237,237,101,61,61,61,176,217,108,72,167,211,136,197,
	98,80,85,21,170,170,22,44,222,188,225,160,170,42,42,43,
	43,193,243,60,100,89,70,83,83,19,234,235,235,67,147,147,
	147,88,90,90,10,93,217,143,225,225,97,218,220,220,164,145,
	145,17,114,56,28,196,243,60,25,12,6,50,153,76,100,54,
	155,137,8,68,4,42,45,45,37,143,199,67,45,45,45,36,
	138,34,173,175,175,211,204,204,12,1,192,147,39,157,116,153,
	121,15,0,244,122,61,155,157,157,221,215,52,173,50,26,141,
	162,64,186,40,157,78,135,72,228,30,222,191,119,160,168,168,
	8,169,84,10,67,67,67,240,251,253,168,169,169,193,238,238,
	174,46,153,76,190,206,100,50,225,43,96,171,213,250,93,54,
	155,77,29,30,30,50,159,207,135,157,157,157,107,96,189,222,
	142,227,227,18,164,211,105,120,189,94,204,207,207,135,226,241,
	56,214,214,214,42,39,38,38,124,151,161,151,79,3,19,4,
	33,40,8,2,9,130,64,29,29,29,4,160,80,249,53,42,
	42,42,104,117,117,149,198,199,199,9,0,94,190,28,99,46,
	151,43,120,13,152,55,206,100,50,251,138,162,132,45,22,75,
	240,98,140,214,214,86,196,227,113,84,87,87,195,237,254,19,
	7,7,60,4,225,87,184,221,110,156,157,157,129,136,116,47,
	94,252,54,99,179,217,216,141,182,151,35,8,2,203,91,87,
	85,85,145,223,239,167,198,198,70,18,4,129,22,22,22,168,
	188,188,92,106,111,111,151,2,129,0,221,10,202,27,231,163,
	40,202,190,197,98,121,13,224,23,77,211,160,40,10,140,70,
	35,70,71,71,81,82,82,2,158,231,247,203,202,190,9,173,
	175,71,83,95,179,188,118,187,229,114,185,48,0,159,170,170,
	56,57,57,1,0,68,34,17,108,108,108,224,244,244,20,99,
	99,191,223,222,246,215,34,8,2,171,173,173,37,143,199,19,
	4,128,199,143,127,166,190,190,62,246,159,160,55,229,75,127,
	255,75,185,203,211,148,79,248,159,128,63,1,82,157,167,207,
	218,88,39,121,0,0,0,0,73,69,78,68,174,66,96,130,
	

};
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //

uppMainWindow_glade::uppMainWindow_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  uppMainWindow = this;
   gmm_data = new GlademmData(get_accel_group());
   newMenuItem = NULL;
   openMenuItem = NULL;
   image9 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-refresh"), Gtk::IconSize(1)));
   reloadMenuItem = NULL;
   saveMenuItem = NULL;
   save_asMenuItem = NULL;
   separatormenuitem1 = NULL;
   quitMenuItem = NULL;
   menuFile_menu = Gtk::manage(new class Gtk::Menu());
   menuFile = NULL;
   programMenuItem = NULL;
   bulkeraseMenuItem = NULL;
   readMenuItem = NULL;
   verifyMenuItem = NULL;
   menuActions_menu = Gtk::manage(new class Gtk::Menu());
   menuActions = NULL;
   menuView = NULL;
   aboutMenuItem = NULL;
   menuHelp_menu = Gtk::manage(new class Gtk::Menu());
   menuHelp = NULL;
   uppMainMenu = Gtk::manage(new class Gtk::MenuBar());
   image4 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-new"), Gtk::IconSize(4)));
   newButton = Gtk::manage(new class Gtk::Button());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   newButtonToolItem = Gtk::manage(new class Gtk::ToolItem());
#endif //
   image5 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-open"), Gtk::IconSize(4)));
   openButton = Gtk::manage(new class Gtk::Button());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   openButtonToolItem = Gtk::manage(new class Gtk::ToolItem());
#endif //
   image6 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-refresh"), Gtk::IconSize(4)));
   reloadButton = Gtk::manage(new class Gtk::Button());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   reloadButtonToolItem = Gtk::manage(new class Gtk::ToolItem());
#endif //
   image7 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-save"), Gtk::IconSize(4)));
   saveButton = Gtk::manage(new class Gtk::Button());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   saveButtonToolItem = Gtk::manage(new class Gtk::ToolItem());
#endif //
   image8 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-save-as"), Gtk::IconSize(4)));
   saveAsButton = Gtk::manage(new class Gtk::Button());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   saveAsButtonToolItem = Gtk::manage(new class Gtk::ToolItem());
#endif //
   image10 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-connect"), Gtk::IconSize(4)));
   connectButton = Gtk::manage(new class Gtk::Button());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   picTypeToolItem = Gtk::manage(new class Gtk::ToolItem());
#endif //
   image11 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-disconnect"), Gtk::IconSize(4)));
   disConnectButton = Gtk::manage(new class Gtk::Button());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem11 = Gtk::manage(new class Gtk::ToolItem());
#endif //
   
   Glib::RefPtr<Gdk::PixbufLoader> _image12_loader=Gdk::PixbufLoader::create();
   _image12_loader->write(hi22_action_piklab_burnchip_png_data, sizeof hi22_action_piklab_burnchip_png_data);
   _image12_loader->close();
   image12 = Gtk::manage(new class Gtk::Image(_image12_loader->get_pixbuf()));
   _image12_loader=Glib::RefPtr<Gdk::PixbufLoader>();
   programButton = Gtk::manage(new class Gtk::Button());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem12 = Gtk::manage(new class Gtk::ToolItem());
#endif //
   
   Glib::RefPtr<Gdk::PixbufLoader> _image13_loader=Gdk::PixbufLoader::create();
   _image13_loader->write(hi22_action_piklab_readchip_png_data, sizeof hi22_action_piklab_readchip_png_data);
   _image13_loader->close();
   image13 = Gtk::manage(new class Gtk::Image(_image13_loader->get_pixbuf()));
   _image13_loader=Glib::RefPtr<Gdk::PixbufLoader>();
   readButton = Gtk::manage(new class Gtk::Button());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem13 = Gtk::manage(new class Gtk::ToolItem());
#endif //
   
   Glib::RefPtr<Gdk::PixbufLoader> _image14_loader=Gdk::PixbufLoader::create();
   _image14_loader->write(hi22_action_piklab_erasechip_png_data, sizeof hi22_action_piklab_erasechip_png_data);
   _image14_loader->close();
   image14 = Gtk::manage(new class Gtk::Image(_image14_loader->get_pixbuf()));
   _image14_loader=Glib::RefPtr<Gdk::PixbufLoader>();
   eraseButton = Gtk::manage(new class Gtk::Button());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem10 = Gtk::manage(new class Gtk::ToolItem());
#endif //
   
   Glib::RefPtr<Gdk::PixbufLoader> _image15_loader=Gdk::PixbufLoader::create();
   _image15_loader->write(hi22_action_piklab_verifychip_png_data, sizeof hi22_action_piklab_verifychip_png_data);
   _image15_loader->close();
   image15 = Gtk::manage(new class Gtk::Image(_image15_loader->get_pixbuf()));
   _image15_loader=Glib::RefPtr<Gdk::PixbufLoader>();
   verifyButton = Gtk::manage(new class Gtk::Button());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem14 = Gtk::manage(new class Gtk::ToolItem());
#endif //
   picTypeCombo = Gtk::manage(new class Gtk::ComboBox());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem15 = Gtk::manage(new class Gtk::ToolItem());
#endif //
   toolBar = Gtk::manage(new class Gtk::Toolbar());
   hexView = Gtk::manage(new class Gtk::TextView());
   scrolledwindow1 = Gtk::manage(new class Gtk::ScrolledWindow());
   statusBar = Gtk::manage(new class Gtk::Statusbar());
   topBox = Gtk::manage(new class Gtk::VBox(false, 0));
   
   
   menuFile_menu->items().push_back(Gtk::Menu_Helpers::StockMenuElem(Gtk::StockID("gtk-new")));
   newMenuItem = (Gtk::ImageMenuItem *)&menuFile_menu->items().back();
   
   menuFile_menu->items().push_back(Gtk::Menu_Helpers::StockMenuElem(Gtk::StockID("gtk-open")));
   openMenuItem = (Gtk::ImageMenuItem *)&menuFile_menu->items().back();
   
   menuFile_menu->items().push_back(Gtk::Menu_Helpers::ImageMenuElem("_Reload", *image9));
   reloadMenuItem = (Gtk::ImageMenuItem *)&menuFile_menu->items().back();
   
   menuFile_menu->items().push_back(Gtk::Menu_Helpers::StockMenuElem(Gtk::StockID("gtk-save")));
   saveMenuItem = (Gtk::ImageMenuItem *)&menuFile_menu->items().back();
   
   menuFile_menu->items().push_back(Gtk::Menu_Helpers::StockMenuElem(Gtk::StockID("gtk-save-as")));
   save_asMenuItem = (Gtk::ImageMenuItem *)&menuFile_menu->items().back();
   
   menuFile_menu->items().push_back(Gtk::Menu_Helpers::SeparatorElem());
   separatormenuitem1 = (Gtk::MenuItem *)&menuFile_menu->items().back();
   
   menuFile_menu->items().push_back(Gtk::Menu_Helpers::StockMenuElem(Gtk::StockID("gtk-quit")));
   quitMenuItem = (Gtk::ImageMenuItem *)&menuFile_menu->items().back();
   
   menuActions_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Program"));
   programMenuItem = (Gtk::MenuItem *)&menuActions_menu->items().back();
   
   menuActions_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("Bulk _Erase"));
   bulkeraseMenuItem = (Gtk::MenuItem *)&menuActions_menu->items().back();
   
   menuActions_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Read"));
   readMenuItem = (Gtk::MenuItem *)&menuActions_menu->items().back();
   
   menuActions_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Verify"));
   verifyMenuItem = (Gtk::MenuItem *)&menuActions_menu->items().back();
   
   menuHelp_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("_About"));
   aboutMenuItem = (Gtk::MenuItem *)&menuHelp_menu->items().back();
   
   uppMainMenu->items().push_back(Gtk::Menu_Helpers::MenuElem("_File", *menuFile_menu));
   menuFile = (Gtk::MenuItem *)&uppMainMenu->items().back();
   
   uppMainMenu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Actions", *menuActions_menu));
   menuActions = (Gtk::MenuItem *)&uppMainMenu->items().back();
   
   uppMainMenu->items().push_back(Gtk::Menu_Helpers::MenuElem("_View"));
   menuView = (Gtk::MenuItem *)&uppMainMenu->items().back();
   
   uppMainMenu->items().push_back(Gtk::Menu_Helpers::MenuElem("_Help", *menuHelp_menu));
   menuHelp = (Gtk::MenuItem *)&uppMainMenu->items().back();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->append(*newButtonToolItem);
#else //
   toolBar->tools().push_back(Gtk::Toolbar_Helpers::Element(*newButton));
   
   Gtk::Widget *newButtonToolItem = toolBar->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->append(*openButtonToolItem);
#else //
   toolBar->tools().push_back(Gtk::Toolbar_Helpers::Element(*openButton));
   
   Gtk::Widget *openButtonToolItem = toolBar->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->append(*reloadButtonToolItem);
#else //
   toolBar->tools().push_back(Gtk::Toolbar_Helpers::Element(*reloadButton));
   
   Gtk::Widget *reloadButtonToolItem = toolBar->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->append(*saveButtonToolItem);
#else //
   toolBar->tools().push_back(Gtk::Toolbar_Helpers::Element(*saveButton));
   
   Gtk::Widget *saveButtonToolItem = toolBar->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->append(*saveAsButtonToolItem);
#else //
   toolBar->tools().push_back(Gtk::Toolbar_Helpers::Element(*saveAsButton));
   
   Gtk::Widget *saveAsButtonToolItem = toolBar->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->append(*picTypeToolItem);
#else //
   toolBar->tools().push_back(Gtk::Toolbar_Helpers::Element(*connectButton));
   
   Gtk::Widget *picTypeToolItem = toolBar->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->append(*toolitem11);
#else //
   toolBar->tools().push_back(Gtk::Toolbar_Helpers::Element(*disConnectButton));
   
   Gtk::Widget *toolitem11 = toolBar->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->append(*toolitem12);
#else //
   toolBar->tools().push_back(Gtk::Toolbar_Helpers::Element(*programButton));
   
   Gtk::Widget *toolitem12 = toolBar->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->append(*toolitem13);
#else //
   toolBar->tools().push_back(Gtk::Toolbar_Helpers::Element(*readButton));
   
   Gtk::Widget *toolitem13 = toolBar->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->append(*toolitem10);
#else //
   toolBar->tools().push_back(Gtk::Toolbar_Helpers::Element(*eraseButton));
   
   Gtk::Widget *toolitem10 = toolBar->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->append(*toolitem14);
#else //
   toolBar->tools().push_back(Gtk::Toolbar_Helpers::Element(*verifyButton));
   
   Gtk::Widget *toolitem14 = toolBar->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->append(*toolitem15);
#else //
   toolBar->tools().push_back(Gtk::Toolbar_Helpers::Element(*picTypeCombo));
   
   Gtk::Widget *toolitem15 = toolBar->tools().back().get_widget();
#endif //
   image9->set_name("image9");
   image9->set_alignment(0.5,0.5);
   image9->set_padding(0,0);
   menuFile_menu->set_name("menuFile_menu");
   menuActions_menu->set_name("menuActions_menu");
   menuHelp_menu->set_name("menuHelp_menu");
   uppMainMenu->set_name("uppMainMenu");
   image4->set_name("image4");
   image4->set_alignment(0.5,0.5);
   image4->set_padding(0,0);
   newButton->set_name("newButton");
   newButton->set_flags(Gtk::CAN_FOCUS);
   newButton->set_relief(Gtk::RELIEF_NORMAL);
   newButton->add(*image4);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   newButtonToolItem->set_name("newButtonToolItem");
   newButtonToolItem->set_visible_horizontal(true);
   newButtonToolItem->set_visible_vertical(true);
   newButtonToolItem->set_is_important(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   newButtonToolItem->add(*newButton);
#endif //
   image5->set_name("image5");
   image5->set_alignment(0.5,0.5);
   image5->set_padding(0,0);
   openButton->set_name("openButton");
   openButton->set_flags(Gtk::CAN_FOCUS);
   openButton->set_relief(Gtk::RELIEF_NORMAL);
   openButton->add(*image5);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   openButtonToolItem->set_name("openButtonToolItem");
   openButtonToolItem->set_visible_horizontal(true);
   openButtonToolItem->set_visible_vertical(true);
   openButtonToolItem->set_is_important(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   openButtonToolItem->add(*openButton);
#endif //
   image6->set_name("image6");
   image6->set_alignment(0.5,0.5);
   image6->set_padding(0,0);
   reloadButton->set_name("reloadButton");
   reloadButton->set_flags(Gtk::CAN_FOCUS);
   reloadButton->set_relief(Gtk::RELIEF_NORMAL);
   reloadButton->add(*image6);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   reloadButtonToolItem->set_name("reloadButtonToolItem");
   reloadButtonToolItem->set_visible_horizontal(true);
   reloadButtonToolItem->set_visible_vertical(true);
   reloadButtonToolItem->set_is_important(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   reloadButtonToolItem->add(*reloadButton);
#endif //
   image7->set_name("image7");
   image7->set_alignment(0.5,0.5);
   image7->set_padding(0,0);
   saveButton->set_name("saveButton");
   saveButton->set_flags(Gtk::CAN_FOCUS);
   saveButton->set_relief(Gtk::RELIEF_NORMAL);
   saveButton->add(*image7);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   saveButtonToolItem->set_name("saveButtonToolItem");
   saveButtonToolItem->set_visible_horizontal(true);
   saveButtonToolItem->set_visible_vertical(true);
   saveButtonToolItem->set_is_important(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   saveButtonToolItem->add(*saveButton);
#endif //
   image8->set_name("image8");
   image8->set_alignment(0.5,0.5);
   image8->set_padding(0,0);
   saveAsButton->set_name("saveAsButton");
   saveAsButton->set_flags(Gtk::CAN_FOCUS);
   saveAsButton->set_relief(Gtk::RELIEF_NORMAL);
   saveAsButton->add(*image8);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   saveAsButtonToolItem->set_name("saveAsButtonToolItem");
   saveAsButtonToolItem->set_visible_horizontal(true);
   saveAsButtonToolItem->set_visible_vertical(true);
   saveAsButtonToolItem->set_is_important(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   saveAsButtonToolItem->add(*saveAsButton);
#endif //
   image10->set_name("image10");
   image10->set_alignment(0.5,0.5);
   image10->set_padding(0,0);
   connectButton->set_name("connectButton");
   connectButton->set_flags(Gtk::CAN_FOCUS);
   connectButton->set_relief(Gtk::RELIEF_NORMAL);
   connectButton->add(*image10);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   picTypeToolItem->set_name("picTypeToolItem");
   picTypeToolItem->set_visible_horizontal(true);
   picTypeToolItem->set_visible_vertical(true);
   picTypeToolItem->set_is_important(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   picTypeToolItem->add(*connectButton);
#endif //
   image11->set_name("image11");
   image11->set_alignment(0.5,0.51);
   image11->set_padding(0,0);
   disConnectButton->set_name("disConnectButton");
   disConnectButton->set_flags(Gtk::CAN_FOCUS);
   disConnectButton->set_relief(Gtk::RELIEF_NORMAL);
   disConnectButton->add(*image11);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem11->set_name("toolitem11");
   toolitem11->set_visible_horizontal(true);
   toolitem11->set_visible_vertical(true);
   toolitem11->set_is_important(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem11->add(*disConnectButton);
#endif //
   image12->set_name("image12");
   image12->set_alignment(0.5,0.5);
   image12->set_padding(0,0);
   programButton->set_name("programButton");
   programButton->set_flags(Gtk::CAN_FOCUS);
   programButton->set_relief(Gtk::RELIEF_NORMAL);
   programButton->add(*image12);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem12->set_name("toolitem12");
   toolitem12->set_visible_horizontal(true);
   toolitem12->set_visible_vertical(true);
   toolitem12->set_is_important(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem12->add(*programButton);
#endif //
   image13->set_name("image13");
   image13->set_alignment(0.5,0.5);
   image13->set_padding(0,0);
   readButton->set_name("readButton");
   readButton->set_flags(Gtk::CAN_FOCUS);
   readButton->set_relief(Gtk::RELIEF_NORMAL);
   readButton->add(*image13);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem13->set_name("toolitem13");
   toolitem13->set_visible_horizontal(true);
   toolitem13->set_visible_vertical(true);
   toolitem13->set_is_important(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem13->add(*readButton);
#endif //
   image14->set_name("image14");
   image14->set_alignment(0.5,0.5);
   image14->set_padding(0,0);
   eraseButton->set_name("eraseButton");
   eraseButton->set_flags(Gtk::CAN_FOCUS);
   eraseButton->set_relief(Gtk::RELIEF_NORMAL);
   eraseButton->add(*image14);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem10->set_name("toolitem10");
   toolitem10->set_visible_horizontal(true);
   toolitem10->set_visible_vertical(true);
   toolitem10->set_is_important(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem10->add(*eraseButton);
#endif //
   image15->set_name("image15");
   image15->set_alignment(0.5,0.5);
   image15->set_padding(0,0);
   verifyButton->set_name("verifyButton");
   verifyButton->set_flags(Gtk::CAN_FOCUS);
   verifyButton->set_relief(Gtk::RELIEF_NORMAL);
   verifyButton->add(*image15);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem14->set_name("toolitem14");
   toolitem14->set_visible_horizontal(true);
   toolitem14->set_visible_vertical(true);
   toolitem14->set_is_important(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem14->add(*verifyButton);
#endif //
   picTypeCombo->set_name("picTypeCombo");
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem15->set_name("toolitem15");
   toolitem15->set_visible_horizontal(true);
   toolitem15->set_visible_vertical(true);
   toolitem15->set_is_important(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem15->add(*picTypeCombo);
#endif //
   toolBar->set_name("toolBar");
   toolBar->set_tooltips(true);
   toolBar->set_toolbar_style(Gtk::TOOLBAR_BOTH);
   toolBar->set_orientation(Gtk::ORIENTATION_HORIZONTAL);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolBar->set_show_arrow(true);
#endif //
   hexView->set_name("hexView");
   hexView->set_flags(Gtk::CAN_FOCUS);
   hexView->set_editable(false);
   hexView->set_cursor_visible(true);
   hexView->set_pixels_above_lines(0);
   hexView->set_pixels_below_lines(0);
   hexView->set_pixels_inside_wrap(0);
   hexView->set_left_margin(0);
   hexView->set_right_margin(0);
   hexView->set_indent(0);
   hexView->set_wrap_mode(Gtk::WRAP_NONE);
   hexView->set_justification(Gtk::JUSTIFY_LEFT);
   scrolledwindow1->set_name("scrolledwindow1");
   scrolledwindow1->set_flags(Gtk::CAN_FOCUS);
   scrolledwindow1->set_shadow_type(Gtk::SHADOW_IN);
   scrolledwindow1->set_policy(Gtk::POLICY_ALWAYS, Gtk::POLICY_ALWAYS);
   scrolledwindow1->property_window_placement().set_value(Gtk::CORNER_TOP_LEFT);
   scrolledwindow1->add(*hexView);
   statusBar->set_name("statusBar");
   topBox->set_name("topBox");
   topBox->pack_start(*uppMainMenu, Gtk::PACK_SHRINK, 0);
   topBox->pack_start(*toolBar, Gtk::PACK_SHRINK, 0);
   topBox->pack_start(*scrolledwindow1);
   topBox->pack_start(*statusBar, Gtk::PACK_SHRINK, 0);
   uppMainWindow->set_name("uppMainWindow");
   uppMainWindow->set_title("UsbPicProg");
   uppMainWindow->set_default_size(800,600);
   uppMainWindow->set_modal(false);
   uppMainWindow->property_window_position().set_value(Gtk::WIN_POS_NONE);
   uppMainWindow->set_resizable(true);
   uppMainWindow->property_destroy_with_parent().set_value(false);
   uppMainWindow->add(*topBox);
   newMenuItem->show();
   openMenuItem->show();
   image9->show();
   reloadMenuItem->show();
   saveMenuItem->show();
   save_asMenuItem->show();
   separatormenuitem1->show();
   quitMenuItem->show();
   menuFile->show();
   programMenuItem->show();
   bulkeraseMenuItem->show();
   readMenuItem->show();
   verifyMenuItem->show();
   menuActions->show();
   menuView->show();
   aboutMenuItem->show();
   menuHelp->show();
   uppMainMenu->show();
   image4->show();
   newButton->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   newButtonToolItem->show();
#endif //
   image5->show();
   openButton->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   openButtonToolItem->show();
#endif //
   image6->show();
   reloadButton->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   reloadButtonToolItem->show();
#endif //
   image7->show();
   saveButton->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   saveButtonToolItem->show();
#endif //
   image8->show();
   saveAsButton->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   saveAsButtonToolItem->show();
#endif //
   image10->show();
   connectButton->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   picTypeToolItem->show();
#endif //
   image11->show();
   disConnectButton->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem11->show();
#endif //
   image12->show();
   programButton->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem12->show();
#endif //
   image13->show();
   readButton->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem13->show();
#endif //
   image14->show();
   eraseButton->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem10->show();
#endif //
   image15->show();
   verifyButton->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem14->show();
#endif //
   picTypeCombo->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem15->show();
#endif //
   toolBar->show();
   hexView->show();
   scrolledwindow1->show();
   statusBar->show();
   topBox->show();
   uppMainWindow->show();
   newMenuItem->signal_activate().connect(SigC::slot(*this, &uppMainWindow_glade::on_new_activate), false);
   openMenuItem->signal_activate().connect(SigC::slot(*this, &uppMainWindow_glade::on_open_activate), false);
   reloadMenuItem->signal_activate().connect(SigC::slot(*this, &uppMainWindow_glade::on_reload_activate), false);
   saveMenuItem->signal_activate().connect(SigC::slot(*this, &uppMainWindow_glade::on_save_activate), false);
   save_asMenuItem->signal_activate().connect(SigC::slot(*this, &uppMainWindow_glade::on_save_as_activate), false);
   quitMenuItem->signal_activate().connect(SigC::slot(*this, &uppMainWindow_glade::on_quit_activate), false);
   programMenuItem->signal_activate().connect(SigC::slot(*this, &uppMainWindow_glade::on_program_activate), false);
   bulkeraseMenuItem->signal_activate().connect(SigC::slot(*this, &uppMainWindow_glade::on_bulkerase_activate), false);
   readMenuItem->signal_activate().connect(SigC::slot(*this, &uppMainWindow_glade::on_read_activate), false);
   verifyMenuItem->signal_activate().connect(SigC::slot(*this, &uppMainWindow_glade::on_verify_activate), false);
   aboutMenuItem->signal_activate().connect(SigC::slot(*this, &uppMainWindow_glade::on_about_activate), false);
   newButton->signal_clicked().connect(SigC::slot(*this, &uppMainWindow_glade::on_newButton_clicked), false);
   openButton->signal_clicked().connect(SigC::slot(*this, &uppMainWindow_glade::on_openButton_clicked), false);
   reloadButton->signal_clicked().connect(SigC::slot(*this, &uppMainWindow_glade::on_reloadButton_clicked), false);
   saveButton->signal_clicked().connect(SigC::slot(*this, &uppMainWindow_glade::on_saveButton_clicked), false);
   saveAsButton->signal_clicked().connect(SigC::slot(*this, &uppMainWindow_glade::on_saveAsButton_clicked), false);
   connectButton->signal_clicked().connect(SigC::slot(*this, &uppMainWindow_glade::on_connect_hardware), false);
   disConnectButton->signal_clicked().connect(SigC::slot(*this, &uppMainWindow_glade::on_disconnect_hardware), false);
   programButton->signal_clicked().connect(SigC::slot(*this, &uppMainWindow_glade::on_program_activate), false);
   readButton->signal_clicked().connect(SigC::slot(*this, &uppMainWindow_glade::on_read_activate), false);
   eraseButton->signal_clicked().connect(SigC::slot(*this, &uppMainWindow_glade::on_bulkerase_activate), false);
   verifyButton->signal_clicked().connect(SigC::slot(*this, &uppMainWindow_glade::on_verify_activate), false);
   picTypeCombo->signal_changed().connect(SigC::slot(*this, &uppMainWindow_glade::on_combo_changed), false);
}

uppMainWindow_glade::~uppMainWindow_glade()
{  delete gmm_data;
}
