#!/opt/local/bin/bash
# This file contains the settings so that the different scripts use
# the same paths etc.
#
# Created by Gustav Johansson 2010-03-11
#

#################################
## SETTINGS, CHANGE STUFF HERE ##
#################################

# This is were we will be working from
WORKDIR="$HOME/projects"
# This is where the ppc version of wxWidgets will be installed.
PREFIX_ppc="$WORKDIR/sw/ppc"
# This is where the i386 version of wxWidgets will be installed.
PREFIX_i386="$WORKDIR/sw/i386"
# This is where the i386 version of wxWidgets will be installed.
PREFIX_x86_64="$WORKDIR/sw/x86_64"
# This is where the ppc version of wxWidgets will be installed.
PREFIX_ppc_cocoa="$WORKDIR/sw/ppc_cocoa"
# This is where the i386 version of wxWidgets will be installed.
PREFIX_i386_cocoa="$WORKDIR/sw/i386_cocoa"
# This is where the i386 version of wxWidgets will be installed.
PREFIX_x86_64_cocoa="$WORKDIR/sw/x86_64_cocoa"
# This is were the final app will be placed
PREFIX_app="$HOME/Temporary"

# Setup which platform we need to support.
# NOTE: You have to have the right SDK installed!
export MACOSX_DEPLOYMENT_TARGET=10.4
sdk_flags=" -isysroot /Developer/SDKs/MacOSX10.5.sdk -mmacosx-version-min=$MACOSX_DEPLOYMENT_TARGET"
sdk_flags_x86=" -isysroot /Developer/SDKs/MacOSX10.5.sdk -mmacosx-version-min=10.5"

#################################
##   END OF SETTINGS, DO NOT   ##
##   CHANGE STUFF AFTER THIS   ##
#################################
